### ISSUE TITLE
Empty parameterOrder attribute for operation tag

### ISSUE THREAD

**Issue by joksnet** [BeSimple/BeSimpleSoapClient#1]
Hello,

When I have a soap method without any parameters, the WSDL _operation_ tag it's generated with the attribute _parameterOrder_ empty. When trying to load the file with .NET `wsdl.exe` I get _This web service does not conform to WS-I Basic Profile v1.1_.

Looking at [WS-I Basic Profile v1.1](http://www.ws-i.org/Profiles/BasicProfile-1.1.html) specification, I found this phase:

> R2305 A wsdl:operation element child of a wsdl:portType element in a DESCRIPTION MUST be constructed so that the parameterOrder attribute, if present, omits at most 1 wsdl:part from the output message. 

I think it refers that the attribute _parameterOrder_ it mustn't be present if empty.

**Comment by joksnet** [comment]
Little patch:

``` patch
diff --git a/ServiceDefinition/Dumper/WsdlDumper.php b/ServiceDefinition/Dumper/WsdlDumper.php
index 97517f7..51aa010 100644
--- a/ServiceDefinition/Dumper/WsdlDumper.php
+++ b/ServiceDefinition/Dumper/WsdlDumper.php
@@ -78,7 +78,9 @@ class WsdlDumper implements DumperInterface
                 $this->qualify($this->getRequestMessageName($method)),
                 $this->qualify($this->getResponseMessageName($method))
             );
-            $portOperation->setAttribute('parameterOrder', implode(' ', array_keys($requestParts)));
+            if (!empty($requestParts)) {
+                $portOperation->setAttribute('parameterOrder', implode(' ', array_keys($requestParts)));
+            }

             $baseBinding = array(
                 'use'           => 'literal',
```

**Comment by francisbesset** [comment]
You have submitted an issue in a bad repository.
Please create an issue in BeSimple/BeSimpleSoapBundle: https://github.com/BeSimple/BeSimpleSoapBundle

**Comment by joksnet** [comment]
Ups. I'm sorry.
