### ISSUE TITLE
Clien timeout option

### ISSUE THREAD

**Issue by carlossg00** [BeSimple/BeSimpleSoapClient#11]
Hello,

Would be great to have the timeout option in the client. [PHP: SoapClient]((http://php.net/manual/en/soapclient.soapclient.php)

``` php
//
// setting a connection timeout (fifteen seconds on the example)
//
$client = new SoapClient($wsdl, array("connection_timeout" => 15));
```

I would create the PR for this feature if I had enough knowledge.

SoapClientBuilder has methods for the creation of the client with options.

``` php
public function withTrace($trace = true)
```

But again don't know how to use them.

Any guidance?
Thanks for your work.

**Comment by francisbesset** [comment]
Please send your PR on new [BeSimple/BeSimpleSoap](http://github.com/BeSimple/BeSimpleSoap) repository.
