### ISSUE TITLE
How to add BeSimpleSoapClient to AppKernel in symfony2

### ISSUE THREAD

**Issue by billgsm** [BeSimple/BeSimpleSoapClient#16]
Hi,

I only installed BeSimpleSoapClient, trying to follow http://besim.pl/SoapBundle/soapclient/configuration.html#client-configuration, I couldn't find any information about adding it to the Kernel. If I don't, I have an error when I try to use my console commands, saying:

```
 [Symfony\Component\Config\Exception\FileLoaderLoadException]
Cannot import resource "....). Looked for namespace "be_simple_soap", found "framework", "securit
  y", "twig", "monolog", "swiftmailer",.....
```

**Comment by alexbogo** [comment]
new BeSimple\SoapClient\SoapClientBuilder(),
