### ISSUE TITLE
Circular references in WSDL cause infinite looping in WsdlDownloader

### ISSUE THREAD

**Issue by jpastoor** [BeSimple/BeSimpleSoapClient#25]
I'm experimenting with Wsdl2PhpGenerator + BeSimple to generate classes and execute SOAP calls based on the WSDLs I'm provided with by the customer.

Some of those WSDL files have circular references in their imports causing the WsdlDonwnloader to loop in the download() and resolveRemoteIncludes methods.

Since I'm quite new to this stuff I wonder if
- Circular References in WSDL and type XMLs is a anti pattern and I should contact the customer about it
- Is it a known issue that the WsdlDownloader does not support it?
- Would people be interested in a patch of me where I prevent redownloading WSDLs that are already resolved?

Thanks in advance,
Joost Pastoor

**Comment by u4415127** [comment]
I'm experience the same issue in WsdlDownloader class. Would you please help provide a patch for this.

Thanks in advance,
Nat

**Comment by jpastoor** [comment]
Hi Nat,

Sorry, I'm not currently working with these libs anymore.

Regards,
Joost
